### ISSUE TITLE
内存问题

### ISSUE THREAD

**Issue by SkyFitz** [chehongshu/ncnnforandroid_objectiondetection_Mobilenetssd#7]
请问下，我用MobileNetSSD_demo 这个demo在android上运行
加载完模型直接返回，重复多次，内存一直在涨。
请问这是哪里有问题？

**Comment by chehongshu** [comment]
内存？你运行一段时间会出现内存爆炸吗？

**Comment by SkyFitz** [comment]
解决了。
![image](https://user-images.githubusercontent.com/48275320/71777605-34e62f80-2fdd-11ea-8437-d493aed24ffe.png)
这个几个静态变量导致的。
多谢了。
